---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csy017-test-redis-deployment
  labels:
    app: csy017-test-redis
    username: csy017
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csy017-test-redis
  template:
    metadata:
      labels:
        app: csy017-test-redis
    spec:
      containers:
        - name: csy017-test-redis
          image: redis:7
          volumeMounts:
          - name: csy017-test-redis
            mountPath: "/data"
          ports: 
          - name: http 
            containerPort: 6379
      volumes:
      - name: csy017-test-redis
        persistentVolumeClaim:
          claimName: csy017-test-redis
