---
apiVersion: v1
kind: Service
metadata:
  name: csy017-test-redis-service
spec:
  type: ClusterIP
  selector:
    app: csy017-test-redis
  ports:
  - name: csy017-test-redis
    port: 6379
    targetPort: 6379
