---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csy017-test-redis
  labels:
    app: csy017-test-redis
    username: csy017
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
