---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-csy017-flask-deployment
  labels:
    app: csy017-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csy017-test-flask
  template:
    metadata:
      labels:
        app: csy017-test-flask
    spec:
      containers:
        - name: csy017-test-flask
          image: csoney017/gene_api:1.0
          imagePullPolicy: Always
          env:
          - name: FLASK_APP
            value: "gene_api.py"
          ports:
          - name: http
            containerPort: 5000
          env: 
            - name: REDIS_IP
              value: csy017-test-redis-service
